apiVersion: v2
name: aws-infra
description: Umbrella chart for ACK-driven AWS infra
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: vpc-controller
    version: 0.1.0
    repository: file://charts/vpc-controller
  - name: iam-controller
    version: 0.1.0
    repository: file://charts/iam-controller
  - name: rds-controller
    version: 0.1.0
    repository: file://charts/rds-controller
  - name: s3-controller
    version: 0.1.0
    repository: file://charts/s3-controller
  - name: kms-controller
    version: 0.1.0
    repository: file://charts/kms-controller
  - name: ec2-controller
    version: 0.1.0
    repository: file://charts/ec2-controller
  - name: autoscaling-controller
    version: 0.1.0
    repository: file://charts/autoscaling-controller
  - name: sns-controller
    version: 0.1.0
    repository: file://charts/sns-controller
  - name: sqs-controller
    version: 0.1.0
    repository: file://charts/sqs-controller
  - name: cwlogs-controller
    version: 0.1.0
    repository: file://charts/cwlogs-controller
  - name: route53-controller
    version: 0.1.0
    repository: file://charts/route53-controller
  - name: peering-controller
    version: 0.1.0
    repository: file://charts/peering-controller
  - name: secretsmgr-controller
    version: 0.1.0
    repository: file://charts/secretsmgr-controller
  - name: cloudtrail-controller
    version: 0.1.0
    repository: file://charts/cloudtrail-controller
  - name: elasticsearch-controller
    version: 0.1.0
    repository: file://charts/elasticsearch-controller
  - name: cdis-vpc-wafv2
    version: 0.1.0
    repository: file://../cdis-vpc-wafv2
    condition: global.cds-vpcwafv2.enabled
    import-values:
      - vpcName
      - installCRD
