enabled: true

iam:
  defaultRoleName: csoc_adminvm        # :contentReference[oaicite:18]{index=18}:contentReference[oaicite:19]{index=19}
  usersPolicyJson: ""                  # :contentReference[oaicite:20]{index=20}:contentReference[oaicite:21]{index=21}

kms:
  createKey: true
  alias: "{{ .Values.vpc.name }}-k8s"  # :contentReference[oaicite:22]{index=22}:contentReference[oaicite:23]{index=23}

keyPair:
  create:        true
  publicKey:     ""                    # will be injected at install time
  keyName:       "{{ .Values.vpc.name }}_automation_dev"   # :contentReference[oaicite:24]{index=24}:contentReference[oaicite:25]{index=25}

randomPasswords:
  length:        20                    # default from nested.yaml
