{{- if and .Values.rds.enabled .Values.secretsManager.enabled -}}
{{- range .Values.instances }}
{{- if and .enabled .createSecret }}
---
apiVersion: secretsmanager.services.k8s.aws/v1alpha1
kind: Secret
metadata:
  name: {{ default (printf "%s-credentials" .dbInstanceIdentifier) .secretName }}
spec:
  # AWS Secret name
  name: {{ default (printf "%s-credentials" .dbInstanceIdentifier) .secretName }}
  secretString: |
    {
      "username": "{{ .masterUsername }}",
      "password": "{{ .masterUserPassword }}"
    }
{{- end }}
{{- end }}
{{- end }}
