{{- if .Values.vpc.enabled }}
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPC
metadata:
  name: {{ include "network.fullname" . }}-vpc
  labels:
    {{- include "network.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}-network
spec:
  scope: Cluster
  cidrBlocks:
    - {{ .Values.vpc.cidrBlock }}
  tags:
    {{- range $k, $v := .Values.vpc.tags }}
    - key: {{ $k }}
      value: {{ $v | quote }}
    {{- end }}
{{- end }}

