---
module:
  project:
    source: ../../../modules/project
    organization: organizations/${data.google_organization.org.id}
    project_name: ${var.project_name}
    folder_id: ${module.folders.folder_id}
    region: ${var.region}
    billing_account: ${var.billing_account}
    enable_apis: 'true'
    disable_services_on_destroy: 'true'
    add_csoc_service_account: true
    csoc_project_id: ${data.terraform_remote_state.org_setup_csoc.project_number}
    activate_apis:
      compute.googleapis.com
      sqladmin.googleapis.com
      container.googleapis.com
      iam.googleapis.com
      containerregistry.googleapis.com
      storage-api.googleapis.com
      servicenetworking.googleapis.com
