---
module:
  - config_files:
    source: ../../shared/modules/k8s_configs
    vpc_name: ${var.vpc_name}
    db_fence_address: ${module.sql_dbs.fence_db_ip}
    db_fence_password: ${var.db_fence_password}
    db_gdcapi_address: ${module.sql_dbs.sheepdog_db_ip}
    db_peregrine_password: ${var.db_peregrine_password}
    db_sheepdog_password: ${var.db_sheepdog_password}
    db_indexd_password: ${var.db_indexd_password}
    db_indexd_address: ${module.sql_dbs.indexd_db_ip}
    hostname: ${var.hostname}
    google_client_secret: ${var.google_client_secret}
    google_client_id: ${var.google_client_id}
    gdcapi_secret_key: ${var.gdcapi_secret_key}
    gdcapi_indexd_password: ${var.gdcapi_indexd_password}
    kube_bucket_name: TBD
    logs_bucket_name: TBD
    dictionary_url: ${var.dictionary_url}
    portal_app: ${var.portal_app}
    config_folder: ${var.config_folder}
    ssl_certificate_id: GCP
    aws_user_key: es AWS key - ignore
    aws_user_key_id: es AWS key - ignore
    indexd_prefix: add later
    mailgun_api_key: ignore for now
