---
module:
  firewall-csoc-ingress-inbound-https:
    source: ../../../modules/firewall
    enable_logging: ${var.https_ingress_enable_logging}
    priority: ${var.https_ingress_priority}
    project_id: ${data.terraform_remote_state.org_setup.project_id}
    direction: ${var.https_ingress_direction}
    name: ${module.vpc-csoc-ingress.network_name}-inbound-https
    network: ${module.vpc-csoc-ingress.network_name}
    protocol: ${var.https_ingress_protocol}
    ports:
      ${var.https_ingress_ports}
    target_tags:
      ${var.https_ingress_target_tags}
