# Default values for global chart
global:
  aws:
  vpcName: "Commons1"
  environment: "prod"
  organization: "Basic Service"

  awsRegion: "us-east-1"
  awsEndpointUrl: ""


  ack:
  acm:
    enabled: false
  acmpca:
    enabled: false
  ecr:
    enabled: false
  ecs:
    enabled: false
  elbv2:
    enabled: false
  emrcontainers:
    enabled: false

  applicationautoscaling:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  cloudfront:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  cloudtrail:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  cloudwatch:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  cloudwatchlogs:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  ec2:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    watchNamespace: [] 
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  eks:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  iam:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  kms:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  lambda:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  opensearchservice:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  rds:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  route53resolver:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  s3:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  s3control:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  secretsmanager:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  sns:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  sqs:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

  wafv2:
    enabled: true
    namespace: ack-system
    replicas: 1
    enableDevelopmentLogging: false
    logLevel: info
    reconcileDefaultMaxConcurrentSyncs: 1
    featureGates: ""
    resourceTags: ""
    leaderElection:
      enabled: false
      namespace: leader-election-namespace
    image:
      repository: controller
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 300Mi

