apiVersion: v1
kind: ConfigMap
metadata:
  name: global
data:
  environment: ${vpc_name}
  hostname: ${hostname}
  revproxy_arn: ${revproxy_arn}
  # Set up hook at https://yourslack.slack.com/apps/manage/custom-integrations
  slack_webhook: 'None'
  gitops_path: ${gitops_path}
